Inputs
mathisrichter/lava-dnf pull request #1
Opened 2021-11-19 14:24 UTC by gkarray

Spike inputs implementations.

Added : 

- src/lava/lib/dnf/inputs/patterns/gauss_pattern/process.py : Contains GaussPattern Process definition.
- src/lava/lib/dnf/inputs/patterns/gauss_pattern/models.py : Contains GaussPattern PyLoihiProcessModel definition.
- src/lava/lib/dnf/inputs/generators/spike_generator/process.py : Contains SpikeGenerator Process definition.
- src/lava/lib/dnf/inputs/generators/spike_generator/models.py : Contains SpikeGenerator PyLoihiProcessModel definition.

- src/lava/lib/dnf/inputs/inputs_test_file.py : Contains example code on how to use GaussPattern + SpikeGenerator processes.

- tests/lava/lib/dnf/inputs/patterns/gauss_pattern/test_process.py : Contains unit tests for GaussPattern Process.
- tests/lava/lib/dnf/inputs/patterns/gauss_pattern/test_models.py : Contains unit tests for GaussPattern PyLoihiProcessModel definition.
- tests/lava/lib/dnf/inputs/generators/spike_generator/test_process.py : Contains unit tests for SpikeGenerator Process definition.
- tests/lava/lib/dnf/inputs/generators/spike_generator/test_models.py : Contains unit tests for SpikeGenerator PyLoihiProcessModel definition.

- Bunch of __init__.py files.

- `.vscode/` line to .gitignore file

Missing : 

- Documentation.
- Actual implementation of unit tests

2021-11-19 14:47 UTC, mathisrichter requested changes
Great work, Ghassen!

We talked about some of these things but I'll repeat them here:
- Add unit tests
- Add docstrings everywhere and comments where appropriate
- Fix all linter and security linter issues (flake8, bandit)
- CI/CD should pass

2021-11-19 14:47 UTC, mathisrichter commented on src/lava/lib/dnf/inputs/generators/spike_generator/models.py
> +        distances = np.where(pattern > MIN_SPIKE_RATE, np.rint(TIME_STEPS_PER_MINUTE / pattern).astype(np.int), 0)
Line is probably too long. Please adhere to 80 character line limits everywhere.

2021-11-19 14:47 UTC, mathisrichter commented on src/lava/lib/dnf/inputs/inputs_test_file.py
> +    main()
This shouldn't go into the repository. Please convert this into unit tests, possibly by hardcoding the expected outcome in the test. We could also use some of it for a tutorial on the spike input generator.

2021-11-19 15:53 UTC, mathisrichter commented
Also, could you move both the spike_generator directory and gauss_pattern directory into inputs directly?

2021-11-21 17:35 UTC, gkarray commented on src/lava/lib/dnf/inputs/generators/spike_generator/models.py
> +        distances = np.where(pattern > MIN_SPIKE_RATE, np.rint(TIME_STEPS_PER_MINUTE / pattern).astype(np.int), 0)
Fixed this in latest commit !

2021-11-21 17:35 UTC, gkarray commented on src/lava/lib/dnf/inputs/inputs_test_file.py
> +    main()
Will fix this on next commit where we'll have unit tests.

2021-11-21 17:38 UTC, gkarray commented
- Added docstrings + comments where appropriate.
- Fixed all linter issues.
- All CI/CD are passing

2021-11-21 17:46 UTC, gkarray commented
- Restructured inputs directory

2021-11-21 18:07 UTC, gkarray commented
I think we might have to change something in GaussPattern process structure if we want it to generalize to non-blocking mode when Lava supports it.

The rationale behind this is the following : 
By having setters for amplitude, mean and stddev parameters individually, we must call _update at the end of each setter.
That way we can have a following use case : 

`gauss_pattern = GaussPattern(shape=shape, amplitude=1500.0, mean=40, stddev=15)
spike_generator = SpikeGenerator(shape=shape)
gauss_pattern.out_ports.a_out.connect(spike_generator.in_ports.a_in)

spike_generator.run(condition=RunSteps(num_steps=42))

gauss_pattern.mean = 30

spike_generator.run(condition=RunSteps(num_steps=42))
spike_generator.stop()`

Calling an additional setter after `gauss_pattern.mean = 30` (for example, `gauss_pattern.stddev = 5`) won't be much of a problem here, since at that point, the runtime is "paused" (Processes have run for 42 time steps in blocking mode and reached the `gauss_pattern.mean = 30` line), so, the changed flag will be set two True two times, and when the Processes re-run again afterwards, it would have the same effect as having set only one variable. 
As a consequence, the gauss pattern will be re-computed and re-sent only one time after both mean and stddev have been changed. 
This re-computation and re-sending and would happen on the first time step of the second `spike_generator.run(condition=RunSteps(num_steps=42))`.

In non-blocking mode however, things might get more complicated.

Since we would want something like this : 

`gauss_pattern = GaussPattern(shape=shape, amplitude=1500.0, mean=40, stddev=15)
spike_generator = SpikeGenerator(shape=shape)
gauss_pattern.out_ports.a_out.connect(spike_generator.in_ports.a_in)

spike_generator.run(condition=RunContinuous())

gauss_pattern.mean = 30
gauss_pattern.stddev = 5

...

spike_generator.stop()`

We may want to bundle the two changes of `mean` and `stddev` into one change, or else, the new gauss pattern might have to be computed and sent two times (first time with only the change to `mean` being effective, second time with both changes to `mean` and `stddev` bein effective).
Put in other words, left as such, if we were in non-blocking mode, setting mean `gauss_pattern.mean = 30` will trigger an update of the changed flag to True.
If next run_spk of the ProcessModel gets executed before setting stddev `gauss_pattern.stddev = 5` line, a call to the gauss method would be issued with the value of mean updated and the value of stddev not updated.
A few time_steps later (after `gauss_pattern.stddev = 5` gets executed), the changed flag will be True again and the run_spk of the ProcessModel will re-compute and re-send a new pattern that would discard the previous one.

2021-11-22 15:22 UTC, gkarray commented on src/lava/lib/dnf/inputs/inputs_test_file.py
> +    main()
Deleted this file in latest commit.

2021-11-22 15:29 UTC, gkarray commented
Added unit tests in last commit.

3 of those will probably fail : 
- `test_compute_first_spike_times` under tests/lava/lib/dnf/unit/inputs/spike_generator/test_models.py
- `test_generate_spikes` under tests/lava/lib/dnf/unit/inputs/spike_generator/test_models.py
- `test_spike_generator_receiving_gauss_pattern` under tests/lava/lib/dnf/acceptance/test_gauss_spike_generator.py

Reason : 
Couldn't patch the call to `np.random.rng()` in line 87 of src/lava/lib/dnf/inputs/spike_generator/models.py to make the results reproduceable. 

Possible correction : 
- Either find a way to patch said call to always use same seed (say, 42)
- Or, add a `seed` Var to the `SpikeGenerator` process and process model.

2021-11-22 17:42 UTC, mathisrichter requested changes
Looks great, just one little thing

2021-11-22 17:42 UTC, mathisrichter commented on src/lava/lib/dnf/inputs/spike_generator/models.py
> +MIN_SPIKE_RATE = 0.5
Could this become a parameter of Process with a default value?

2021-11-22 18:07 UTC, gkarray commented on src/lava/lib/dnf/inputs/spike_generator/models.py
> +MIN_SPIKE_RATE = 0.5
It could, but then we would have to add two `Var`, each corresponding to one of these constants, since it's the only way to pass data to the ProcessModel. 

Are we okay with this ?

2021-11-22 20:38 UTC, gkarray commented on src/lava/lib/dnf/inputs/spike_generator/models.py
> +MIN_SPIKE_RATE = 0.5
Addressed this in latest commit.

2021-11-22 20:46 UTC, gkarray commented
Resolved randomness related unit tests failures.

There seems to be another issue that makes some unit tests fail sometimes and pass some other times ... 

Namely, this issue has been seen in : 
- `test_generate_spikes` under tests/lava/lib/dnf/unit/inputs/spike_generator/test_models.py
- `test_change_pattern_triggers_computation_and_send` under tests/lava/lib/dnf/unit/inputs/gauss_pattern/test_models.py

It may be due to non-deterministic arrival timestep for messages sent through Ports.
This has to be further investigated.

2021-11-22 21:11 UTC, mathisrichter approved these changes

2021-11-22 21:12 UTC, merged